name = "tick"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.34"
dot_env = "~> 0.2"
sqlight = "~> 0.9"
gleam_http = "~> 3.5"
mist = "~> 0.15"
simplifile = "~> 1.2"
wisp = "~> 0.10"
migrant = "~> 0.2"
gleam_erlang = "~> 0.24"
gleam_json = "~> 0.7"
crossbar = "~> 1.3"
argon2_elixir = "~> 3.2"
ids = "~> 0.12"

[dev-dependencies]
gleeunit = "~> 1.0"
