name = "tick"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.32"
wisp = "~> 0.8"
mist = "~> 0.15"
dot_env = "~> 0.2"
gleam_json = "~> 0.7"
sqlight = "~> 0.9"
gleam_http = "~> 3.5"
migrant = "~> 0.1"
gleam_erlang = "~> 0.24"
simplifile = "~> 0.4"
apollo = "~> 0.1"

[dev-dependencies]
gleeunit = "~> 1.0"
