[build]
builder = "DOCKERFILE"
dockerfilePath = "api.Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/api/health"
sleepApplication = true
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
